# 监听端口
listen_port: 3000

# 启用插件
enable_plugins:
  - template-plugins
  - pay-code

# 插件配置
plugins_config:
  # pay-code 收款码插件
  # 用于获取收款二维码
  pay-code:
    # 默认展示 可选 wechat(微信赞赏码) alipay(支付宝收款码) qq(QQ收款码) wechatpay(微信收款码)
    default: alipay
    # 收款码图片URL（为null则不展示） 绝对路径或相对路径
    alipay: ./pay-code/static/alipay.png
    wechat: null
    qq: null
    wechatpay: null
  
  # color 颜色插件
  # 用于快速获取常用的颜色
  color:
    # 定义颜色列表 参考下方的格式定义
    colors:
      pink: fa7298
    