name: Deploy

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            SERVER_HOST: ${{ secrets.SERVER_HOST }}
            SERVER_PORT: ${{ secrets.SERVER_PORT }}
            SERVER_USER: ${{ secrets.SERVER_USER }}
            SERVER_KEY: ${{ secrets.SERVER_KEY }}
            SERVER_PATH: ${{ secrets.SERVER_PATH }}
            CONFIG_FILE: ${{ secrets.CONFIG_FILE }}
        steps:
            - name: Pulling source code from the repository
              uses: actions/checkout@v3

            - name: Setting the node version
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install project dependencies
              run: yarn install

            - name: Build project
              run: |
                  yarn build
                  mv ./dist/code ./dist/nia
                  cd ./dist/nia
                  echo "${{ secrets.CONFIG_FILE }}" > .config.yaml
                  cd ../../

            # - name: Deploy project to server
            #   uses: cross-the-world/ssh-scp-ssh-pipelines@latest
            #   with:
            #       host: ${{secrets.SERVER_HOST}}
            #       user: ${{secrets.SERVER_USER}}
            #       key: ${{secrets.SERVER_KEY}}
            #       port: ${{secrets.SERVER_PORT}}
            #       scp: |
            #           './nia/*' => $${{secrets.SERVER_PATH}}/nia/

            - name: Deploy project to server
              uses: easingthemes/ssh-deploy@main
              with:
                  SSH_PRIVATE_KEY: ${{ secrets.SERVER_KEY }}
                  SOURCE: dist/nia/
                  REMOTE_HOST: ${{ secrets.SERVER_HOST }}
                  REMOTE_USER: ${{ secrets.SERVER_USER }}
                  TARGET: ${{secrets.SERVER_PATH}}/nia
                  REMOTE_PORT: ${{ secrets.SERVER_PORT }}
